server.port=8081

# Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/employee_db?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.quartz.job-store-type=memory
# JasperReports Server
jrs.server.url=http://localhost:8080/jasperserver-pro
jrs.server.username=jasperadmin
jrs.server.password=jasperadmin
jrs.server.report-path=/reports/demo/test
jrs.server.output-path=/reports/demo/output

